### ISSUE TITLE
APIstoTest not being read correctly from config file

### ISSUE THREAD

**Issue by gmannGlasswall** [filetrust/sdk-rebuild-eval#5]
The below config is giving this error `WARNING:GlasswallLogger:Failed to deserialize test case file C:\GWRegTester\Testconfigs\BMP - Analysis Vs Protect.yml.`  I had added the APIsToTest item to check it. This config file works fine in the c# version.

```
Bugs:
    - BugNumber: 0                                            
      Name: BMP - Analysis Vs Protect
      Description: BMP - Analysis Vs Protect
      FileType: bmp                                            
      Input:
        - Path: C:\Test_Data\Reg_Tester_sets\SampleCoverageSets\BMP
          Recurse: true                                         
      ContentManagementSwitches:        # This will be ignored...No CM Switches in BMP                        
        - ConfigSwitch: pdfConfig                        
          ContentManagementFlags:                               
            acroform: sanitise
            metadata: sanitise
            javascript: sanitise
            actions_all: sanitise
            embedded_files: sanitise
            internal_hyperlinks: sanitise
            external_hyperlinks: sanitise
            
      Tests:
        - !OneAgainstAnotherTestMode                            
          AnalysisAgainstProtect: true        
          APIsToTest: 
           - FiletoFile

```
